### ISSUE TITLE
Appears to have stopped working in iOS 10.3

### ISSUE THREAD

**Issue by Jered** [chemzqm/pinch-zoom#1]
Any plans on updating to work with latest versions of iOS?

**Comment by sandstrom** [comment]
It's an awesome library! ⛵️  But we've also run into trouble on iOS 10.3.

**Comment by chemzqm** [comment]
It's already fixed at https://github.com/mobkits/pinch-zoom/commit/4873aa55adbaa861d613ba6b8d9a837afdf0f34c

**Comment by sandstrom** [comment]
@chemzqm Awesome! 😄 

Let's close this issue!
